timestamp:
  key: time
  visible: true
  format: "02/01/2006 15:04:05"

logger:
  key: logger
  visible: true
  padding: 0

caller:
  key: caller
  visible: false
  padding: 0

level:
  key: severity
  visible: true
  padding: 5
  colors:
    debug:
    info:
    warn:
    error:
    fatal:

message:
  key: message
  padding: 0

fields:
  pid:
    visible: true
  unformatted:
    visible: false
  uuid:
    visible: true
    color: [32,12,34]
